{'T': None,
 '_Tp': None,
 '__addressof': '_Tp*\n    __addressof(_Tp& __r) noexcept\n    ',
 '__cxx11': 'namespace',
 '__float128': None,
 '__gnu_cxx': 'namespace',
 '__int128': None,
 '__x': 'bool\n      operator!=(const _Tp& __x, const _Tp& __y)\n      ',
 '__y': 'bool\n      operator>=(const _Tp& __x, const _Tp& __y)\n      ',
 'auto': None,
 'bool': [],
 'char': None,
 'char16_t': None,
 'char32_t': None,
 'double': None,
 'float': None,
 'int': None,
 'long': None,
 'nullptr_t': [],
 'ptrdiff_t': [],
 'rel_ops': 'namespace',
 'short': None,
 'signed': None,
 'size_t': [],
 'std': 'namespace',
 'uint_least16_t': [],
 'uint_least32_t': [],
 'unsigned': None,
 'void': None,
 'wchar_t': None}
