{'Maybe': None,
 'T': None,
 '__float128': None,
 '__int128': None,
 'auto': None,
 'bool': [],
 'boxed_type': [],
 'char': None,
 'char16_t': None,
 'char32_t': None,
 'double': None,
 'float': None,
 'int': None,
 'isNothing': 'bool isNothing() const ',
 'is_nothing': 'bool is_nothing ',
 'long': None,
 'short': None,
 'signed': None,
 'unsigned': None,
 'value': 'T value',
 'void': None,
 'wchar_t': None}
